import { AppointmentModalProvider } from "@/hooks/useAppointmentModal";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { CreateAppointmentModal } from "@/components/CreateAppointmentModal";
import { ScheduleAppointmentModal } from "@/components/ScheduleAppointmentModal";
import { AddPatientModal } from "@/components/AddPatientModal";
import { EditAppointmentModal } from "@/components/EditAppointmentModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppointmentModalProvider>
          {children}
          <Toaster />
          <CreateAppointmentModal />
          <ScheduleAppointmentModal />
          <AddPatientModal />
          <EditAppointmentModal />
        </AppointmentModalProvider>
      </body>
    </html>
  );
}
